spring:
  application:
    name: alter-eco-api
  datasource:
    url: jdbc:postgresql://ec2-54-228-250-82.eu-west-1.compute.amazonaws.com:5432/d7cehdv1kl8rh8
    username: seqppzdktjmzzo
    password: 79bea1489f3e3f1ac418bbd0a34e365a35ae7198d5304e0fac3554f99428a755
    hikari:
      maximum-pool-size: 2
springdoc:
  swagger-ui:
    path: /api/swagger.html
  api-docs:
    path: /api/swagger
operation:
  approval:
    waiting-for-approve-m: 10
    resolved-m: 10
    waiting-for-approve-count: 2
    resolved-count: 2
    reward:
      approve-attendee: 100
      complete-attendee: 100
      trash-attendee: 20
      creator: 200